# Generated by Django 4.1.6 on 2023-02-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_alter_pet_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="weight",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
