# Generated by Django 4.1.6 on 2023-02-07 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0002_alter_group_created_at"),
        ("pets", "0003_alter_pet_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pets",
                to="groups.group",
            ),
        ),
    ]
