# Generated by Django 4.1.6 on 2023-02-07 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scientific_name", models.CharField(max_length=50, unique=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 2, 6, 21, 4, 28, 324804)
                    ),
                ),
            ],
        ),
    ]
